jobs:
- job: "Windows_${{parameters.arch}}"
  pool:
    vmImage: "windows-latest"
  steps:
  - script: |
      cd $(Build.BinariesDirectory)
      call "${{parameters.vcvarsPath}}" ${{parameters.vcvarsArg}}
      cmake -G "NMake Makefiles" $(Build.SourcesDirectory)
      set CL=/MP
      nmake
    displayName: "Build"
  - template: "artifacts-steps.yml"
    parameters:
      name: "Windows (${{parameters.arch}})"
