jobs:
- job: "msvc_${{parameters.bits}}"
  displayName: "MSVC (${{parameters.bits}} bit)"
  pool:
    vmImage: "windows-latest"
  steps:
  - script: |
      cd $(Build.BinariesDirectory)
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars${{parameters.bits}}.bat"
      cmake -G "NMake Makefiles" $(Build.SourcesDirectory)
      set CL=/MP
      nmake
    displayName: "Build"
  - template: "artifacts-steps.yml"
    parameters:
      name: "Windows ${{parameters.bits}} bit (MSVC)"
